version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: master
    schedule:
      interval: "daily"
      timezone: "CET"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "Dependabot"
    ignore:
      - dependency-name: "*"`
        update-types: ["version-update:semver-major"]
