name: Slack Notification
on: pull_request_target

jobs:
  slackNotification:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Send slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: dependabot-alerts
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Dependabot PR has been opened, hold on tight :rocket'
